services:
  kpress-app-post-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3032:3032"
    depends_on:
      - kpress-db-post

  kpress-db-post:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"